version: '3.8'

services:
  app:
    build: .
    container_name: essentialnews
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0.22
    container_name: mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: 0513
      MYSQL_DATABASE: test
      MYSQL_USER: newsuser
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  db_data:

